# Generated by Django 2.1.2 on 2018-10-18 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome da atividade')),
                ('duracao', models.TimeField(verbose_name='duração')),
                ('data', models.DateField(verbose_name='data da atividade')),
                ('hora', models.TimeField(verbose_name='hora da atividade')),
                ('tipo', models.IntegerField(choices=[(0, 'Palestra'), (1, 'Minicurso')], verbose_name='tipo de atividade')),
                ('inscritos', models.ManyToManyField(blank=True, related_name='inscritos', to=settings.AUTH_USER_MODEL, verbose_name='inscritos')),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do evento')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='dono do evento')),
                ('minicursos', models.ManyToManyField(blank=True, related_name='minicursos', to='evento.Atividade', verbose_name='minicursos')),
                ('palestras', models.ManyToManyField(blank=True, related_name='palestras', to='evento.Atividade', verbose_name='palestras')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do palestrante')),
            ],
            options={
                'verbose_name': 'palestrante',
                'verbose_name_plural': 'palestrantes',
            },
        ),
        migrations.AddField(
            model_name='atividade',
            name='palestrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='evento.Palestrante', verbose_name='palestrante'),
        ),
    ]
